### ISSUE TITLE
Update site-wide settings

### ISSUE THREAD

**Issue by tensaida** [AY2223S1-CS2103T-T13-1/tp#10]
- [ ] ... as described in the guide [Using Jekyll for project documentation @SE-EDU/guides](https://se-education.org/guides/tutorials/jekyll.html).
- [ ] The text AB-3 in docs\_sass\minima\_base.scss needs updating too (it comes into play when you convert documentation to PDF formats)

**Comment by gunbux** [comment]
I'm actually not sure what to do here. maybe someone else can give it a shot
