### ISSUE TITLE
[PE-D][Tester C] Incomplete error message for incorrect tag parameter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T13-1/tp#171]
- Error message does not mention that white space is not allowed when entering the tag parameter.
- Attached below is a screenshot of the error message for your reference.

![image.png](https://raw.githubusercontent.com/hanwenlai/ped/main/files/b6515e6a-2937-4edd-a992-0ba215ed4a08.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: hanwenlai/ped#2

**Comment by yeojunjie** [comment]
Thank you for your suggestion! Unfortunately, we are unable to enhance the quality of our error messages during the semester because of feature freeze restrictions. We will close this issue to keep our Issues page neat.
