### ISSUE TITLE
Update DG

### ISSUE THREAD

**Issue by LuYiting0913** [AY2223S1-CS2103T-T13-1/tp#76]

**Comment by yeojunjie** [comment]
# Diagrams to Update
Diagrams are listed in order of appearance in the Developer Guide.
- [ ] Update `ArchitectureSequenceDiagram.png`
- [X] Update `UiClassDiagram.png`
- [ ] Update `LogicClassDiagram.png`
- [ ] Update `DeleteSequenceDiagram.png`
- [ ] Update `ParserClasses.png`
- [ ] Update `ModelClassDiagram.png`
- [ ] Remove `BetterModelClassDiagram.png`
- [ ] Update `StorageClassDiagram.png`
- [ ] Remove `UndoRedoState*.png`
- [ ] Remove `UndoSequenceDiagram.png`
- [ ] Remove `CommitActivityDiagram.png`
